version: '3'
services:
  app:
    container_name: app  
    build: ./docker/php
    volumes:
      - ./app:/var/www/app
    working_dir: /var/www/app
  nginx:
    image: nginx 
    container_name: nginx
    ports:
      - 80:80 
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - app
